/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 C:\Users\kenta\r3f-1\kurodenwa.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kurodenwa.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.68, -0.62]}>
        <mesh geometry={nodes.HandData.geometry} material={materials.Body} />
        <mesh geometry={nodes.HandData_1.geometry} material={materials.Body} />
      </group>
      <group position={[0, 1.48, 0.24]} rotation={[Math.PI / 4, 0, 0]}>
        <mesh geometry={nodes.DialData.geometry} material={materials.Body} />
        <mesh geometry={nodes.DialData_1.geometry} material={materials.Body} />
        <mesh geometry={nodes.DialData_2.geometry} material={materials.Body} />
      </group>
      <mesh geometry={nodes.Stopper.geometry} material={materials.Stopper} position={[0, 1.48, 0.24]} rotation={[Math.PI / 4, 0.09, 0]} scale={[0.47, 1, 0.47]} />
      <mesh geometry={nodes.CenterPoleData.geometry} material={materials.Body} />
      <mesh geometry={nodes.CenterPoleData_1.geometry} material={materials.Index} />
      <mesh geometry={nodes.BodyData001.geometry} material={materials.Index} />
      <mesh geometry={nodes.BodyData001_1.geometry} material={materials.Body} />
    </group>
  )
}

useGLTF.preload('/kurodenwa.gltf')
