/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 C:\Users\kenta\r3f-1\kurodenwa.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kurodenwa.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.68, -0.62]}>
        <mesh geometry={nodes.HandData.geometry} material={nodes.HandData.material} />
        <mesh geometry={nodes.HandData_1.geometry} material={nodes.HandData_1.material} />
      </group>
      <group position={[0, 1.48, 0.24]} rotation={[Math.PI / 4, -Math.PI / 3, 0]} scale={[0.96, 1, 0.96]}>
        <mesh geometry={nodes.DialData.geometry} material={nodes.DialData.material} />
        <mesh geometry={nodes.DialData_1.geometry} material={nodes.DialData_1.material} />
        <mesh geometry={nodes.DialData_2.geometry} material={nodes.DialData_2.material} />
      </group>
      <mesh geometry={nodes.CenterPole.geometry} material={nodes.CenterPole.material} />
      <mesh geometry={nodes.Stopper.geometry} material={nodes.Stopper.material} position={[0, 1.48, 0.24]} rotation={[Math.PI / 4, 0, 0]} scale={[0.47, 1, 0.47]} />
      <mesh geometry={nodes.BodyData.geometry} material={nodes.BodyData.material} />
      <mesh geometry={nodes.BodyData_1.geometry} material={nodes.BodyData_1.material} />
    </group>
  )
}

useGLTF.preload('/kurodenwa.gltf')
